package com.kindle.kinbook.dao;

import com.kindle.kinbook.bean.ActionCategory;

public interface ActionCategoryMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table action_category
	 * @mbggenerated  Tue Oct 20 22:18:39 CST 2015
	 */
	int deleteByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table action_category
	 * @mbggenerated  Tue Oct 20 22:18:39 CST 2015
	 */
	int insert(ActionCategory record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table action_category
	 * @mbggenerated  Tue Oct 20 22:18:39 CST 2015
	 */
	int insertSelective(ActionCategory record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table action_category
	 * @mbggenerated  Tue Oct 20 22:18:39 CST 2015
	 */
	ActionCategory selectByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table action_category
	 * @mbggenerated  Tue Oct 20 22:18:39 CST 2015
	 */
	int updateByPrimaryKeySelective(ActionCategory record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table action_category
	 * @mbggenerated  Tue Oct 20 22:18:39 CST 2015
	 */
	int updateByPrimaryKey(ActionCategory record);
}