package com.kindle.kinbook.dao;

import com.kindle.kinbook.bean.AvatarMapper;

public interface AvatarMapperMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table avatar_mapper
	 * @mbggenerated  Tue Oct 20 22:18:39 CST 2015
	 */
	int deleteByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table avatar_mapper
	 * @mbggenerated  Tue Oct 20 22:18:39 CST 2015
	 */
	int insert(AvatarMapper record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table avatar_mapper
	 * @mbggenerated  Tue Oct 20 22:18:39 CST 2015
	 */
	int insertSelective(AvatarMapper record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table avatar_mapper
	 * @mbggenerated  Tue Oct 20 22:18:39 CST 2015
	 */
	AvatarMapper selectByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table avatar_mapper
	 * @mbggenerated  Tue Oct 20 22:18:39 CST 2015
	 */
	int updateByPrimaryKeySelective(AvatarMapper record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table avatar_mapper
	 * @mbggenerated  Tue Oct 20 22:18:39 CST 2015
	 */
	int updateByPrimaryKey(AvatarMapper record);
}