package com.kindle.kinbook.dao;

import java.util.List;

import com.kindle.kinbook.bean.Book;
import com.kindle.kinbook.pojo.BookInfoBasic;
import com.kindle.kinbook.pojo.BookInfoDetail;
import com.kindle.kinbook.pojo.QueryConditionItem1;

public interface BookMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table book
	 * @mbggenerated  Tue Oct 20 22:18:39 CST 2015
	 */
	int deleteByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table book
	 * @mbggenerated  Tue Oct 20 22:18:39 CST 2015
	 */
	int insert(Book record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table book
	 * @mbggenerated  Tue Oct 20 22:18:39 CST 2015
	 */
	int insertSelective(Book record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table book
	 * @mbggenerated  Tue Oct 20 22:18:39 CST 2015
	 */
	Book selectByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table book
	 * @mbggenerated  Tue Oct 20 22:18:39 CST 2015
	 */
	int updateByPrimaryKeySelective(Book record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table book
	 * @mbggenerated  Tue Oct 20 22:18:39 CST 2015
	 */
	int updateByPrimaryKey(Book record);
	
	BookInfoDetail getBookInfoDetailById(int bookId);

    BookInfoBasic getBookInfoBasicById(int bookId);

    List<BookInfoBasic> getBasicBookInfoByCategoryAsce(QueryConditionItem1 queryConditionItem1);

    List<BookInfoBasic> getBasicBookInfoByCategoryDesc(QueryConditionItem1 queryConditionItem1);

    List<BookInfoBasic> getBasicBookInfoByRatingAsce(QueryConditionItem1 queryConditionItem1);

    List<BookInfoBasic> getBasicBookInfoByRatingDesc(QueryConditionItem1 queryConditionItem1);

    List<BookInfoBasic> getBasicBookInfoRealtedToAuthorByRatingDesc(String author);
}