package com.kindle.kinbook.dao;

import com.kindle.kinbook.bean.BookCategory;

public interface BookCategoryMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table book_category
	 * @mbggenerated  Tue Oct 20 22:18:39 CST 2015
	 */
	int deleteByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table book_category
	 * @mbggenerated  Tue Oct 20 22:18:39 CST 2015
	 */
	int insert(BookCategory record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table book_category
	 * @mbggenerated  Tue Oct 20 22:18:39 CST 2015
	 */
	int insertSelective(BookCategory record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table book_category
	 * @mbggenerated  Tue Oct 20 22:18:39 CST 2015
	 */
	BookCategory selectByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table book_category
	 * @mbggenerated  Tue Oct 20 22:18:39 CST 2015
	 */
	int updateByPrimaryKeySelective(BookCategory record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table book_category
	 * @mbggenerated  Tue Oct 20 22:18:39 CST 2015
	 */
	int updateByPrimaryKey(BookCategory record);
}