package com.kindle.kinbook.dao;

import com.kindle.kinbook.bean.BookCoverMapper;

public interface BookCoverMapperMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table book_cover_mapper
	 * @mbggenerated  Tue Oct 20 22:18:39 CST 2015
	 */
	int deleteByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table book_cover_mapper
	 * @mbggenerated  Tue Oct 20 22:18:39 CST 2015
	 */
	int insert(BookCoverMapper record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table book_cover_mapper
	 * @mbggenerated  Tue Oct 20 22:18:39 CST 2015
	 */
	int insertSelective(BookCoverMapper record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table book_cover_mapper
	 * @mbggenerated  Tue Oct 20 22:18:39 CST 2015
	 */
	BookCoverMapper selectByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table book_cover_mapper
	 * @mbggenerated  Tue Oct 20 22:18:39 CST 2015
	 */
	int updateByPrimaryKeySelective(BookCoverMapper record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table book_cover_mapper
	 * @mbggenerated  Tue Oct 20 22:18:39 CST 2015
	 */
	int updateByPrimaryKey(BookCoverMapper record);
}