package com.kindle.kinbook.dao;

import com.kindle.kinbook.bean.BookLog;

public interface BookLogMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table book_log
	 * @mbggenerated  Tue Oct 20 22:18:39 CST 2015
	 */
	int deleteByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table book_log
	 * @mbggenerated  Tue Oct 20 22:18:39 CST 2015
	 */
	int insert(BookLog record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table book_log
	 * @mbggenerated  Tue Oct 20 22:18:39 CST 2015
	 */
	int insertSelective(BookLog record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table book_log
	 * @mbggenerated  Tue Oct 20 22:18:39 CST 2015
	 */
	BookLog selectByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table book_log
	 * @mbggenerated  Tue Oct 20 22:18:39 CST 2015
	 */
	int updateByPrimaryKeySelective(BookLog record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table book_log
	 * @mbggenerated  Tue Oct 20 22:18:39 CST 2015
	 */
	int updateByPrimaryKey(BookLog record);
}