package com.kindle.kinbook.dao;

import com.kindle.kinbook.bean.CollectionMap;

public interface CollectionMapMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table collection_map
	 * @mbggenerated  Tue Oct 20 22:18:39 CST 2015
	 */
	int deleteByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table collection_map
	 * @mbggenerated  Tue Oct 20 22:18:39 CST 2015
	 */
	int insert(CollectionMap record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table collection_map
	 * @mbggenerated  Tue Oct 20 22:18:39 CST 2015
	 */
	int insertSelective(CollectionMap record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table collection_map
	 * @mbggenerated  Tue Oct 20 22:18:39 CST 2015
	 */
	CollectionMap selectByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table collection_map
	 * @mbggenerated  Tue Oct 20 22:18:39 CST 2015
	 */
	int updateByPrimaryKeySelective(CollectionMap record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table collection_map
	 * @mbggenerated  Tue Oct 20 22:18:39 CST 2015
	 */
	int updateByPrimaryKey(CollectionMap record);
}