package com.kindle.kinbook.dao;

import com.kindle.kinbook.bean.EbookResources;

public interface EbookResourcesMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ebook_resources
	 * @mbggenerated  Tue Oct 20 22:18:39 CST 2015
	 */
	int deleteByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ebook_resources
	 * @mbggenerated  Tue Oct 20 22:18:39 CST 2015
	 */
	int insert(EbookResources record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ebook_resources
	 * @mbggenerated  Tue Oct 20 22:18:39 CST 2015
	 */
	int insertSelective(EbookResources record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ebook_resources
	 * @mbggenerated  Tue Oct 20 22:18:39 CST 2015
	 */
	EbookResources selectByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ebook_resources
	 * @mbggenerated  Tue Oct 20 22:18:39 CST 2015
	 */
	int updateByPrimaryKeySelective(EbookResources record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ebook_resources
	 * @mbggenerated  Tue Oct 20 22:18:39 CST 2015
	 */
	int updateByPrimaryKey(EbookResources record);
}