package com.kindle.kinbook.dao;

import com.kindle.kinbook.bean.EbookFileMapper;

public interface EbookFileMapperMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ebook_file_mapper
	 * @mbggenerated  Tue Oct 20 22:18:39 CST 2015
	 */
	int deleteByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ebook_file_mapper
	 * @mbggenerated  Tue Oct 20 22:18:39 CST 2015
	 */
	int insert(EbookFileMapper record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ebook_file_mapper
	 * @mbggenerated  Tue Oct 20 22:18:39 CST 2015
	 */
	int insertSelective(EbookFileMapper record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ebook_file_mapper
	 * @mbggenerated  Tue Oct 20 22:18:39 CST 2015
	 */
	EbookFileMapper selectByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ebook_file_mapper
	 * @mbggenerated  Tue Oct 20 22:18:39 CST 2015
	 */
	int updateByPrimaryKeySelective(EbookFileMapper record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ebook_file_mapper
	 * @mbggenerated  Tue Oct 20 22:18:39 CST 2015
	 */
	int updateByPrimaryKey(EbookFileMapper record);
}