package com.kindle.kinbook.dao;

import com.kindle.kinbook.bean.GroupHasUserKey;

public interface GroupHasUserMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table group_has_user
	 * @mbggenerated  Tue Oct 20 22:18:39 CST 2015
	 */
	int deleteByPrimaryKey(GroupHasUserKey key);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table group_has_user
	 * @mbggenerated  Tue Oct 20 22:18:39 CST 2015
	 */
	int insert(GroupHasUserKey record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table group_has_user
	 * @mbggenerated  Tue Oct 20 22:18:39 CST 2015
	 */
	int insertSelective(GroupHasUserKey record);
}