package com.kindle.kinbook.dao;

import com.kindle.kinbook.bean.RoleHasGroupKey;

public interface RoleHasGroupMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table role_has_group
	 * @mbggenerated  Tue Oct 20 22:18:39 CST 2015
	 */
	int deleteByPrimaryKey(RoleHasGroupKey key);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table role_has_group
	 * @mbggenerated  Tue Oct 20 22:18:39 CST 2015
	 */
	int insert(RoleHasGroupKey record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table role_has_group
	 * @mbggenerated  Tue Oct 20 22:18:39 CST 2015
	 */
	int insertSelective(RoleHasGroupKey record);
}