package com.kindle.kinbook.dao;

import java.util.Date;

import com.kindle.kinbook.bean.UserProperties;

public interface UserPropertiesMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table user_properties
	 * @mbggenerated  Tue Oct 20 22:18:39 CST 2015
	 */
	int deleteByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table user_properties
	 * @mbggenerated  Tue Oct 20 22:18:39 CST 2015
	 */
	int insert(UserProperties record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table user_properties
	 * @mbggenerated  Tue Oct 20 22:18:39 CST 2015
	 */
	int insertSelective(UserProperties record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table user_properties
	 * @mbggenerated  Tue Oct 20 22:18:39 CST 2015
	 */
	UserProperties selectByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table user_properties
	 * @mbggenerated  Tue Oct 20 22:18:39 CST 2015
	 */
	int updateByPrimaryKeySelective(UserProperties record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table user_properties
	 * @mbggenerated  Tue Oct 20 22:18:39 CST 2015
	 */
	int updateByPrimaryKey(UserProperties record);
	
	
	Date getLastLoginDate(int userId);

    int getUserWealth(int userId);

    void updateUserWealthByUserId(UserProperties userProperties);
}