package com.kindle.kinbook.dao;

import com.kindle.kinbook.bean.UserLog;

public interface UserLogMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table user_log
	 * @mbggenerated  Tue Oct 20 22:18:39 CST 2015
	 */
	int deleteByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table user_log
	 * @mbggenerated  Tue Oct 20 22:18:39 CST 2015
	 */
	int insert(UserLog record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table user_log
	 * @mbggenerated  Tue Oct 20 22:18:39 CST 2015
	 */
	int insertSelective(UserLog record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table user_log
	 * @mbggenerated  Tue Oct 20 22:18:39 CST 2015
	 */
	UserLog selectByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table user_log
	 * @mbggenerated  Tue Oct 20 22:18:39 CST 2015
	 */
	int updateByPrimaryKeySelective(UserLog record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table user_log
	 * @mbggenerated  Tue Oct 20 22:18:39 CST 2015
	 */
	int updateByPrimaryKey(UserLog record);
}