package com.kindle.kinbook.dao;

import com.kindle.kinbook.bean.UserDetail;

public interface UserDetailMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table user_detail
	 * @mbggenerated  Tue Oct 20 22:18:39 CST 2015
	 */
	int deleteByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table user_detail
	 * @mbggenerated  Tue Oct 20 22:18:39 CST 2015
	 */
	int insert(UserDetail record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table user_detail
	 * @mbggenerated  Tue Oct 20 22:18:39 CST 2015
	 */
	int insertSelective(UserDetail record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table user_detail
	 * @mbggenerated  Tue Oct 20 22:18:39 CST 2015
	 */
	UserDetail selectByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table user_detail
	 * @mbggenerated  Tue Oct 20 22:18:39 CST 2015
	 */
	int updateByPrimaryKeySelective(UserDetail record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table user_detail
	 * @mbggenerated  Tue Oct 20 22:18:39 CST 2015
	 */
	int updateByPrimaryKey(UserDetail record);
}