package com.kindle.kinbook.bean;

public class ActionCategory {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column action_category.id
     *
     * @mbggenerated Tue Oct 20 22:18:39 CST 2015
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column action_category.action
     *
     * @mbggenerated Tue Oct 20 22:18:39 CST 2015
     */
    private String action;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column action_category.id
     *
     * @return the value of action_category.id
     *
     * @mbggenerated Tue Oct 20 22:18:39 CST 2015
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column action_category.id
     *
     * @param id the value for action_category.id
     *
     * @mbggenerated Tue Oct 20 22:18:39 CST 2015
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column action_category.action
     *
     * @return the value of action_category.action
     *
     * @mbggenerated Tue Oct 20 22:18:39 CST 2015
     */
    public String getAction() {
        return action;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column action_category.action
     *
     * @param action the value for action_category.action
     *
     * @mbggenerated Tue Oct 20 22:18:39 CST 2015
     */
    public void setAction(String action) {
        this.action = action;
    }
}