package com.kindle.kinbook.bean;

public class AvatarMapper {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column avatar_mapper.id
     *
     * @mbggenerated Tue Oct 20 22:18:39 CST 2015
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column avatar_mapper.file_name
     *
     * @mbggenerated Tue Oct 20 22:18:39 CST 2015
     */
    private String file_name;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column avatar_mapper.id
     *
     * @return the value of avatar_mapper.id
     *
     * @mbggenerated Tue Oct 20 22:18:39 CST 2015
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column avatar_mapper.id
     *
     * @param id the value for avatar_mapper.id
     *
     * @mbggenerated Tue Oct 20 22:18:39 CST 2015
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column avatar_mapper.file_name
     *
     * @return the value of avatar_mapper.file_name
     *
     * @mbggenerated Tue Oct 20 22:18:39 CST 2015
     */
    public String getFile_name() {
        return file_name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column avatar_mapper.file_name
     *
     * @param file_name the value for avatar_mapper.file_name
     *
     * @mbggenerated Tue Oct 20 22:18:39 CST 2015
     */
    public void setFile_name(String file_name) {
        this.file_name = file_name;
    }
}