package com.kindle.kinbook.bean;

public class Book {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column book.id
     *
     * @mbggenerated Tue Oct 20 22:18:39 CST 2015
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column book.book_name
     *
     * @mbggenerated Tue Oct 20 22:18:39 CST 2015
     */
    private String book_name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column book.author
     *
     * @mbggenerated Tue Oct 20 22:18:39 CST 2015
     */
    private String author;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column book.publisher
     *
     * @mbggenerated Tue Oct 20 22:18:39 CST 2015
     */
    private String publisher;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column book.publish_date
     *
     * @mbggenerated Tue Oct 20 22:18:39 CST 2015
     */
    private String publish_date;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column book.page
     *
     * @mbggenerated Tue Oct 20 22:18:39 CST 2015
     */
    private String page;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column book.price
     *
     * @mbggenerated Tue Oct 20 22:18:39 CST 2015
     */
    private String price;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column book.isbn
     *
     * @mbggenerated Tue Oct 20 22:18:39 CST 2015
     */
    private String isbn;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column book.rating_num
     *
     * @mbggenerated Tue Oct 20 22:18:39 CST 2015
     */
    private String rating_num;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column book.author_intro
     *
     * @mbggenerated Tue Oct 20 22:18:39 CST 2015
     */
    private String author_intro;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column book.book_intro
     *
     * @mbggenerated Tue Oct 20 22:18:39 CST 2015
     */
    private String book_intro;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column book.category_id
     *
     * @mbggenerated Tue Oct 20 22:18:39 CST 2015
     */
    private Integer category_id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column book.cover_link
     *
     * @mbggenerated Tue Oct 20 22:18:39 CST 2015
     */
    private Integer cover_link;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column book.douban_link
     *
     * @mbggenerated Tue Oct 20 22:18:39 CST 2015
     */
    private String douban_link;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column book.ebook_link
     *
     * @mbggenerated Tue Oct 20 22:18:39 CST 2015
     */
    private Integer ebook_link;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column book.id
     *
     * @return the value of book.id
     *
     * @mbggenerated Tue Oct 20 22:18:39 CST 2015
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column book.id
     *
     * @param id the value for book.id
     *
     * @mbggenerated Tue Oct 20 22:18:39 CST 2015
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column book.book_name
     *
     * @return the value of book.book_name
     *
     * @mbggenerated Tue Oct 20 22:18:39 CST 2015
     */
    public String getBook_name() {
        return book_name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column book.book_name
     *
     * @param book_name the value for book.book_name
     *
     * @mbggenerated Tue Oct 20 22:18:39 CST 2015
     */
    public void setBook_name(String book_name) {
        this.book_name = book_name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column book.author
     *
     * @return the value of book.author
     *
     * @mbggenerated Tue Oct 20 22:18:39 CST 2015
     */
    public String getAuthor() {
        return author;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column book.author
     *
     * @param author the value for book.author
     *
     * @mbggenerated Tue Oct 20 22:18:39 CST 2015
     */
    public void setAuthor(String author) {
        this.author = author;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column book.publisher
     *
     * @return the value of book.publisher
     *
     * @mbggenerated Tue Oct 20 22:18:39 CST 2015
     */
    public String getPublisher() {
        return publisher;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column book.publisher
     *
     * @param publisher the value for book.publisher
     *
     * @mbggenerated Tue Oct 20 22:18:39 CST 2015
     */
    public void setPublisher(String publisher) {
        this.publisher = publisher;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column book.publish_date
     *
     * @return the value of book.publish_date
     *
     * @mbggenerated Tue Oct 20 22:18:39 CST 2015
     */
    public String getPublish_date() {
        return publish_date;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column book.publish_date
     *
     * @param publish_date the value for book.publish_date
     *
     * @mbggenerated Tue Oct 20 22:18:39 CST 2015
     */
    public void setPublish_date(String publish_date) {
        this.publish_date = publish_date;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column book.page
     *
     * @return the value of book.page
     *
     * @mbggenerated Tue Oct 20 22:18:39 CST 2015
     */
    public String getPage() {
        return page;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column book.page
     *
     * @param page the value for book.page
     *
     * @mbggenerated Tue Oct 20 22:18:39 CST 2015
     */
    public void setPage(String page) {
        this.page = page;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column book.price
     *
     * @return the value of book.price
     *
     * @mbggenerated Tue Oct 20 22:18:39 CST 2015
     */
    public String getPrice() {
        return price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column book.price
     *
     * @param price the value for book.price
     *
     * @mbggenerated Tue Oct 20 22:18:39 CST 2015
     */
    public void setPrice(String price) {
        this.price = price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column book.isbn
     *
     * @return the value of book.isbn
     *
     * @mbggenerated Tue Oct 20 22:18:39 CST 2015
     */
    public String getIsbn() {
        return isbn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column book.isbn
     *
     * @param isbn the value for book.isbn
     *
     * @mbggenerated Tue Oct 20 22:18:39 CST 2015
     */
    public void setIsbn(String isbn) {
        this.isbn = isbn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column book.rating_num
     *
     * @return the value of book.rating_num
     *
     * @mbggenerated Tue Oct 20 22:18:39 CST 2015
     */
    public String getRating_num() {
        return rating_num;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column book.rating_num
     *
     * @param rating_num the value for book.rating_num
     *
     * @mbggenerated Tue Oct 20 22:18:39 CST 2015
     */
    public void setRating_num(String rating_num) {
        this.rating_num = rating_num;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column book.author_intro
     *
     * @return the value of book.author_intro
     *
     * @mbggenerated Tue Oct 20 22:18:39 CST 2015
     */
    public String getAuthor_intro() {
        return author_intro;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column book.author_intro
     *
     * @param author_intro the value for book.author_intro
     *
     * @mbggenerated Tue Oct 20 22:18:39 CST 2015
     */
    public void setAuthor_intro(String author_intro) {
        this.author_intro = author_intro;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column book.book_intro
     *
     * @return the value of book.book_intro
     *
     * @mbggenerated Tue Oct 20 22:18:39 CST 2015
     */
    public String getBook_intro() {
        return book_intro;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column book.book_intro
     *
     * @param book_intro the value for book.book_intro
     *
     * @mbggenerated Tue Oct 20 22:18:39 CST 2015
     */
    public void setBook_intro(String book_intro) {
        this.book_intro = book_intro;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column book.category_id
     *
     * @return the value of book.category_id
     *
     * @mbggenerated Tue Oct 20 22:18:39 CST 2015
     */
    public Integer getCategory_id() {
        return category_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column book.category_id
     *
     * @param category_id the value for book.category_id
     *
     * @mbggenerated Tue Oct 20 22:18:39 CST 2015
     */
    public void setCategory_id(Integer category_id) {
        this.category_id = category_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column book.cover_link
     *
     * @return the value of book.cover_link
     *
     * @mbggenerated Tue Oct 20 22:18:39 CST 2015
     */
    public Integer getCover_link() {
        return cover_link;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column book.cover_link
     *
     * @param cover_link the value for book.cover_link
     *
     * @mbggenerated Tue Oct 20 22:18:39 CST 2015
     */
    public void setCover_link(Integer cover_link) {
        this.cover_link = cover_link;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column book.douban_link
     *
     * @return the value of book.douban_link
     *
     * @mbggenerated Tue Oct 20 22:18:39 CST 2015
     */
    public String getDouban_link() {
        return douban_link;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column book.douban_link
     *
     * @param douban_link the value for book.douban_link
     *
     * @mbggenerated Tue Oct 20 22:18:39 CST 2015
     */
    public void setDouban_link(String douban_link) {
        this.douban_link = douban_link;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column book.ebook_link
     *
     * @return the value of book.ebook_link
     *
     * @mbggenerated Tue Oct 20 22:18:39 CST 2015
     */
    public Integer getEbook_link() {
        return ebook_link;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column book.ebook_link
     *
     * @param ebook_link the value for book.ebook_link
     *
     * @mbggenerated Tue Oct 20 22:18:39 CST 2015
     */
    public void setEbook_link(Integer ebook_link) {
        this.ebook_link = ebook_link;
    }

	@Override
	public String toString() {
		return "Book [id=" + id + ", book_name=" + book_name + ", author="
				+ author + ", publisher=" + publisher + ", publish_date="
				+ publish_date + ", page=" + page + ", price=" + price
				+ ", isbn=" + isbn + ", rating_num=" + rating_num
				+ ", author_intro=" + author_intro + ", book_intro="
				+ book_intro + ", category_id=" + category_id + ", cover_link="
				+ cover_link + ", douban_link=" + douban_link + ", ebook_link="
				+ ebook_link + "]";
	}
}