package com.kindle.kinbook.bean;

import java.util.Date;

public class BookLog {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column book_log.id
     *
     * @mbggenerated Tue Oct 20 22:18:39 CST 2015
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column book_log.book_id
     *
     * @mbggenerated Tue Oct 20 22:18:39 CST 2015
     */
    private Integer book_id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column book_log.upload_person
     *
     * @mbggenerated Tue Oct 20 22:18:39 CST 2015
     */
    private Integer upload_person;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column book_log.upload_date
     *
     * @mbggenerated Tue Oct 20 22:18:39 CST 2015
     */
    private Date upload_date;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column book_log.view_counts
     *
     * @mbggenerated Tue Oct 20 22:18:39 CST 2015
     */
    private Integer view_counts;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column book_log.download_counts
     *
     * @mbggenerated Tue Oct 20 22:18:39 CST 2015
     */
    private Integer download_counts;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column book_log.collect_times
     *
     * @mbggenerated Tue Oct 20 22:18:39 CST 2015
     */
    private Integer collect_times;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column book_log.id
     *
     * @return the value of book_log.id
     *
     * @mbggenerated Tue Oct 20 22:18:39 CST 2015
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column book_log.id
     *
     * @param id the value for book_log.id
     *
     * @mbggenerated Tue Oct 20 22:18:39 CST 2015
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column book_log.book_id
     *
     * @return the value of book_log.book_id
     *
     * @mbggenerated Tue Oct 20 22:18:39 CST 2015
     */
    public Integer getBook_id() {
        return book_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column book_log.book_id
     *
     * @param book_id the value for book_log.book_id
     *
     * @mbggenerated Tue Oct 20 22:18:39 CST 2015
     */
    public void setBook_id(Integer book_id) {
        this.book_id = book_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column book_log.upload_person
     *
     * @return the value of book_log.upload_person
     *
     * @mbggenerated Tue Oct 20 22:18:39 CST 2015
     */
    public Integer getUpload_person() {
        return upload_person;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column book_log.upload_person
     *
     * @param upload_person the value for book_log.upload_person
     *
     * @mbggenerated Tue Oct 20 22:18:39 CST 2015
     */
    public void setUpload_person(Integer upload_person) {
        this.upload_person = upload_person;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column book_log.upload_date
     *
     * @return the value of book_log.upload_date
     *
     * @mbggenerated Tue Oct 20 22:18:39 CST 2015
     */
    public Date getUpload_date() {
        return upload_date;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column book_log.upload_date
     *
     * @param upload_date the value for book_log.upload_date
     *
     * @mbggenerated Tue Oct 20 22:18:39 CST 2015
     */
    public void setUpload_date(Date upload_date) {
        this.upload_date = upload_date;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column book_log.view_counts
     *
     * @return the value of book_log.view_counts
     *
     * @mbggenerated Tue Oct 20 22:18:39 CST 2015
     */
    public Integer getView_counts() {
        return view_counts;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column book_log.view_counts
     *
     * @param view_counts the value for book_log.view_counts
     *
     * @mbggenerated Tue Oct 20 22:18:39 CST 2015
     */
    public void setView_counts(Integer view_counts) {
        this.view_counts = view_counts;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column book_log.download_counts
     *
     * @return the value of book_log.download_counts
     *
     * @mbggenerated Tue Oct 20 22:18:39 CST 2015
     */
    public Integer getDownload_counts() {
        return download_counts;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column book_log.download_counts
     *
     * @param download_counts the value for book_log.download_counts
     *
     * @mbggenerated Tue Oct 20 22:18:39 CST 2015
     */
    public void setDownload_counts(Integer download_counts) {
        this.download_counts = download_counts;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column book_log.collect_times
     *
     * @return the value of book_log.collect_times
     *
     * @mbggenerated Tue Oct 20 22:18:39 CST 2015
     */
    public Integer getCollect_times() {
        return collect_times;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column book_log.collect_times
     *
     * @param collect_times the value for book_log.collect_times
     *
     * @mbggenerated Tue Oct 20 22:18:39 CST 2015
     */
    public void setCollect_times(Integer collect_times) {
        this.collect_times = collect_times;
    }
}