package com.kindle.kinbook.bean;

public class BookCategory {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column book_category.id
     *
     * @mbggenerated Tue Oct 20 22:18:39 CST 2015
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column book_category.book_category
     *
     * @mbggenerated Tue Oct 20 22:18:39 CST 2015
     */
    private String book_category;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column book_category.id
     *
     * @return the value of book_category.id
     *
     * @mbggenerated Tue Oct 20 22:18:39 CST 2015
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column book_category.id
     *
     * @param id the value for book_category.id
     *
     * @mbggenerated Tue Oct 20 22:18:39 CST 2015
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column book_category.book_category
     *
     * @return the value of book_category.book_category
     *
     * @mbggenerated Tue Oct 20 22:18:39 CST 2015
     */
    public String getBook_category() {
        return book_category;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column book_category.book_category
     *
     * @param book_category the value for book_category.book_category
     *
     * @mbggenerated Tue Oct 20 22:18:39 CST 2015
     */
    public void setBook_category(String book_category) {
        this.book_category = book_category;
    }
}