package com.kindle.kinbook.bean;

public class BookCoverMapper {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column book_cover_mapper.id
     *
     * @mbggenerated Tue Oct 20 22:18:39 CST 2015
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column book_cover_mapper.filename
     *
     * @mbggenerated Tue Oct 20 22:18:39 CST 2015
     */
    private String filename;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column book_cover_mapper.id
     *
     * @return the value of book_cover_mapper.id
     *
     * @mbggenerated Tue Oct 20 22:18:39 CST 2015
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column book_cover_mapper.id
     *
     * @param id the value for book_cover_mapper.id
     *
     * @mbggenerated Tue Oct 20 22:18:39 CST 2015
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column book_cover_mapper.filename
     *
     * @return the value of book_cover_mapper.filename
     *
     * @mbggenerated Tue Oct 20 22:18:39 CST 2015
     */
    public String getFilename() {
        return filename;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column book_cover_mapper.filename
     *
     * @param filename the value for book_cover_mapper.filename
     *
     * @mbggenerated Tue Oct 20 22:18:39 CST 2015
     */
    public void setFilename(String filename) {
        this.filename = filename;
    }
}