package com.kindle.kinbook.bean;

import java.util.Date;

public class CollectionMap {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column collection_map.id
     *
     * @mbggenerated Tue Oct 20 22:18:39 CST 2015
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column collection_map.book_id
     *
     * @mbggenerated Tue Oct 20 22:18:39 CST 2015
     */
    private Integer book_id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column collection_map.user_id
     *
     * @mbggenerated Tue Oct 20 22:18:39 CST 2015
     */
    private Integer user_id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column collection_map.collect_date
     *
     * @mbggenerated Tue Oct 20 22:18:39 CST 2015
     */
    private Date collect_date;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column collection_map.status
     *
     * @mbggenerated Tue Oct 20 22:18:39 CST 2015
     */
    private Integer status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column collection_map.notified
     *
     * @mbggenerated Tue Oct 20 22:18:39 CST 2015
     */
    private Boolean notified;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column collection_map.id
     *
     * @return the value of collection_map.id
     *
     * @mbggenerated Tue Oct 20 22:18:39 CST 2015
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column collection_map.id
     *
     * @param id the value for collection_map.id
     *
     * @mbggenerated Tue Oct 20 22:18:39 CST 2015
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column collection_map.book_id
     *
     * @return the value of collection_map.book_id
     *
     * @mbggenerated Tue Oct 20 22:18:39 CST 2015
     */
    public Integer getBook_id() {
        return book_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column collection_map.book_id
     *
     * @param book_id the value for collection_map.book_id
     *
     * @mbggenerated Tue Oct 20 22:18:39 CST 2015
     */
    public void setBook_id(Integer book_id) {
        this.book_id = book_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column collection_map.user_id
     *
     * @return the value of collection_map.user_id
     *
     * @mbggenerated Tue Oct 20 22:18:39 CST 2015
     */
    public Integer getUser_id() {
        return user_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column collection_map.user_id
     *
     * @param user_id the value for collection_map.user_id
     *
     * @mbggenerated Tue Oct 20 22:18:39 CST 2015
     */
    public void setUser_id(Integer user_id) {
        this.user_id = user_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column collection_map.collect_date
     *
     * @return the value of collection_map.collect_date
     *
     * @mbggenerated Tue Oct 20 22:18:39 CST 2015
     */
    public Date getCollect_date() {
        return collect_date;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column collection_map.collect_date
     *
     * @param collect_date the value for collection_map.collect_date
     *
     * @mbggenerated Tue Oct 20 22:18:39 CST 2015
     */
    public void setCollect_date(Date collect_date) {
        this.collect_date = collect_date;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column collection_map.status
     *
     * @return the value of collection_map.status
     *
     * @mbggenerated Tue Oct 20 22:18:39 CST 2015
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column collection_map.status
     *
     * @param status the value for collection_map.status
     *
     * @mbggenerated Tue Oct 20 22:18:39 CST 2015
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column collection_map.notified
     *
     * @return the value of collection_map.notified
     *
     * @mbggenerated Tue Oct 20 22:18:39 CST 2015
     */
    public Boolean getNotified() {
        return notified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column collection_map.notified
     *
     * @param notified the value for collection_map.notified
     *
     * @mbggenerated Tue Oct 20 22:18:39 CST 2015
     */
    public void setNotified(Boolean notified) {
        this.notified = notified;
    }
}