package com.kindle.kinbook.bean;

public class EbookResources {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ebook_resources.id
     *
     * @mbggenerated Tue Oct 20 22:18:39 CST 2015
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ebook_resources.mobi_format
     *
     * @mbggenerated Tue Oct 20 22:18:39 CST 2015
     */
    private Integer mobi_format;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ebook_resources.azw_format
     *
     * @mbggenerated Tue Oct 20 22:18:39 CST 2015
     */
    private Integer azw_format;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ebook_resources.word_format
     *
     * @mbggenerated Tue Oct 20 22:18:39 CST 2015
     */
    private Integer word_format;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ebook_resources.html_format
     *
     * @mbggenerated Tue Oct 20 22:18:39 CST 2015
     */
    private Integer html_format;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ebook_resources.rtf_format
     *
     * @mbggenerated Tue Oct 20 22:18:39 CST 2015
     */
    private Integer rtf_format;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ebook_resources.picture_format
     *
     * @mbggenerated Tue Oct 20 22:18:39 CST 2015
     */
    private Integer picture_format;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ebook_resources.pdf_format
     *
     * @mbggenerated Tue Oct 20 22:18:39 CST 2015
     */
    private Integer pdf_format;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ebook_resources.zip_format
     *
     * @mbggenerated Tue Oct 20 22:18:39 CST 2015
     */
    private Integer zip_format;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ebook_resources.id
     *
     * @return the value of ebook_resources.id
     *
     * @mbggenerated Tue Oct 20 22:18:39 CST 2015
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ebook_resources.id
     *
     * @param id the value for ebook_resources.id
     *
     * @mbggenerated Tue Oct 20 22:18:39 CST 2015
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ebook_resources.mobi_format
     *
     * @return the value of ebook_resources.mobi_format
     *
     * @mbggenerated Tue Oct 20 22:18:39 CST 2015
     */
    public Integer getMobi_format() {
        return mobi_format;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ebook_resources.mobi_format
     *
     * @param mobi_format the value for ebook_resources.mobi_format
     *
     * @mbggenerated Tue Oct 20 22:18:39 CST 2015
     */
    public void setMobi_format(Integer mobi_format) {
        this.mobi_format = mobi_format;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ebook_resources.azw_format
     *
     * @return the value of ebook_resources.azw_format
     *
     * @mbggenerated Tue Oct 20 22:18:39 CST 2015
     */
    public Integer getAzw_format() {
        return azw_format;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ebook_resources.azw_format
     *
     * @param azw_format the value for ebook_resources.azw_format
     *
     * @mbggenerated Tue Oct 20 22:18:39 CST 2015
     */
    public void setAzw_format(Integer azw_format) {
        this.azw_format = azw_format;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ebook_resources.word_format
     *
     * @return the value of ebook_resources.word_format
     *
     * @mbggenerated Tue Oct 20 22:18:39 CST 2015
     */
    public Integer getWord_format() {
        return word_format;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ebook_resources.word_format
     *
     * @param word_format the value for ebook_resources.word_format
     *
     * @mbggenerated Tue Oct 20 22:18:39 CST 2015
     */
    public void setWord_format(Integer word_format) {
        this.word_format = word_format;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ebook_resources.html_format
     *
     * @return the value of ebook_resources.html_format
     *
     * @mbggenerated Tue Oct 20 22:18:39 CST 2015
     */
    public Integer getHtml_format() {
        return html_format;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ebook_resources.html_format
     *
     * @param html_format the value for ebook_resources.html_format
     *
     * @mbggenerated Tue Oct 20 22:18:39 CST 2015
     */
    public void setHtml_format(Integer html_format) {
        this.html_format = html_format;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ebook_resources.rtf_format
     *
     * @return the value of ebook_resources.rtf_format
     *
     * @mbggenerated Tue Oct 20 22:18:39 CST 2015
     */
    public Integer getRtf_format() {
        return rtf_format;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ebook_resources.rtf_format
     *
     * @param rtf_format the value for ebook_resources.rtf_format
     *
     * @mbggenerated Tue Oct 20 22:18:39 CST 2015
     */
    public void setRtf_format(Integer rtf_format) {
        this.rtf_format = rtf_format;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ebook_resources.picture_format
     *
     * @return the value of ebook_resources.picture_format
     *
     * @mbggenerated Tue Oct 20 22:18:39 CST 2015
     */
    public Integer getPicture_format() {
        return picture_format;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ebook_resources.picture_format
     *
     * @param picture_format the value for ebook_resources.picture_format
     *
     * @mbggenerated Tue Oct 20 22:18:39 CST 2015
     */
    public void setPicture_format(Integer picture_format) {
        this.picture_format = picture_format;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ebook_resources.pdf_format
     *
     * @return the value of ebook_resources.pdf_format
     *
     * @mbggenerated Tue Oct 20 22:18:39 CST 2015
     */
    public Integer getPdf_format() {
        return pdf_format;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ebook_resources.pdf_format
     *
     * @param pdf_format the value for ebook_resources.pdf_format
     *
     * @mbggenerated Tue Oct 20 22:18:39 CST 2015
     */
    public void setPdf_format(Integer pdf_format) {
        this.pdf_format = pdf_format;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ebook_resources.zip_format
     *
     * @return the value of ebook_resources.zip_format
     *
     * @mbggenerated Tue Oct 20 22:18:39 CST 2015
     */
    public Integer getZip_format() {
        return zip_format;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ebook_resources.zip_format
     *
     * @param zip_format the value for ebook_resources.zip_format
     *
     * @mbggenerated Tue Oct 20 22:18:39 CST 2015
     */
    public void setZip_format(Integer zip_format) {
        this.zip_format = zip_format;
    }
}