package com.kindle.kinbook.bean;

public class EbookFileMapper {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ebook_file_mapper.id
     *
     * @mbggenerated Tue Oct 20 22:18:39 CST 2015
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ebook_file_mapper.filename
     *
     * @mbggenerated Tue Oct 20 22:18:39 CST 2015
     */
    private String filename;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ebook_file_mapper.realfilename
     *
     * @mbggenerated Tue Oct 20 22:18:39 CST 2015
     */
    private String realfilename;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ebook_file_mapper.id
     *
     * @return the value of ebook_file_mapper.id
     *
     * @mbggenerated Tue Oct 20 22:18:39 CST 2015
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ebook_file_mapper.id
     *
     * @param id the value for ebook_file_mapper.id
     *
     * @mbggenerated Tue Oct 20 22:18:39 CST 2015
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ebook_file_mapper.filename
     *
     * @return the value of ebook_file_mapper.filename
     *
     * @mbggenerated Tue Oct 20 22:18:39 CST 2015
     */
    public String getFilename() {
        return filename;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ebook_file_mapper.filename
     *
     * @param filename the value for ebook_file_mapper.filename
     *
     * @mbggenerated Tue Oct 20 22:18:39 CST 2015
     */
    public void setFilename(String filename) {
        this.filename = filename;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ebook_file_mapper.realfilename
     *
     * @return the value of ebook_file_mapper.realfilename
     *
     * @mbggenerated Tue Oct 20 22:18:39 CST 2015
     */
    public String getRealfilename() {
        return realfilename;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ebook_file_mapper.realfilename
     *
     * @param realfilename the value for ebook_file_mapper.realfilename
     *
     * @mbggenerated Tue Oct 20 22:18:39 CST 2015
     */
    public void setRealfilename(String realfilename) {
        this.realfilename = realfilename;
    }
}