package com.kindle.kinbook.bean;

public class GroupHasUserKey {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column group_has_user.group_id
     *
     * @mbggenerated Tue Oct 20 22:18:39 CST 2015
     */
    private Integer group_id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column group_has_user.user_id
     *
     * @mbggenerated Tue Oct 20 22:18:39 CST 2015
     */
    private Integer user_id;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column group_has_user.group_id
     *
     * @return the value of group_has_user.group_id
     *
     * @mbggenerated Tue Oct 20 22:18:39 CST 2015
     */
    public Integer getGroup_id() {
        return group_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column group_has_user.group_id
     *
     * @param group_id the value for group_has_user.group_id
     *
     * @mbggenerated Tue Oct 20 22:18:39 CST 2015
     */
    public void setGroup_id(Integer group_id) {
        this.group_id = group_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column group_has_user.user_id
     *
     * @return the value of group_has_user.user_id
     *
     * @mbggenerated Tue Oct 20 22:18:39 CST 2015
     */
    public Integer getUser_id() {
        return user_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column group_has_user.user_id
     *
     * @param user_id the value for group_has_user.user_id
     *
     * @mbggenerated Tue Oct 20 22:18:39 CST 2015
     */
    public void setUser_id(Integer user_id) {
        this.user_id = user_id;
    }
}