package com.kindle.kinbook.bean;

public class RoleHasGroupKey {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column role_has_group.role_id
     *
     * @mbggenerated Tue Oct 20 22:18:39 CST 2015
     */
    private Integer role_id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column role_has_group.group_id
     *
     * @mbggenerated Tue Oct 20 22:18:39 CST 2015
     */
    private Integer group_id;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column role_has_group.role_id
     *
     * @return the value of role_has_group.role_id
     *
     * @mbggenerated Tue Oct 20 22:18:39 CST 2015
     */
    public Integer getRole_id() {
        return role_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column role_has_group.role_id
     *
     * @param role_id the value for role_has_group.role_id
     *
     * @mbggenerated Tue Oct 20 22:18:39 CST 2015
     */
    public void setRole_id(Integer role_id) {
        this.role_id = role_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column role_has_group.group_id
     *
     * @return the value of role_has_group.group_id
     *
     * @mbggenerated Tue Oct 20 22:18:39 CST 2015
     */
    public Integer getGroup_id() {
        return group_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column role_has_group.group_id
     *
     * @param group_id the value for role_has_group.group_id
     *
     * @mbggenerated Tue Oct 20 22:18:39 CST 2015
     */
    public void setGroup_id(Integer group_id) {
        this.group_id = group_id;
    }
}