package com.kindle.kinbook.bean;

import java.util.Date;

public class UserProperties {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_properties.id
     *
     * @mbggenerated Tue Oct 20 22:18:39 CST 2015
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_properties.user_id
     *
     * @mbggenerated Tue Oct 20 22:18:39 CST 2015
     */
    private Integer user_id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_properties.status
     *
     * @mbggenerated Tue Oct 20 22:18:39 CST 2015
     */
    private Integer status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_properties.wealth
     *
     * @mbggenerated Tue Oct 20 22:18:39 CST 2015
     */
    private Integer wealth;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_properties.create_date
     *
     * @mbggenerated Tue Oct 20 22:18:39 CST 2015
     */
    private Date create_date;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_properties.last_login_date
     *
     * @mbggenerated Tue Oct 20 22:18:39 CST 2015
     */
    private Date last_login_date;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_properties.id
     *
     * @return the value of user_properties.id
     *
     * @mbggenerated Tue Oct 20 22:18:39 CST 2015
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_properties.id
     *
     * @param id the value for user_properties.id
     *
     * @mbggenerated Tue Oct 20 22:18:39 CST 2015
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_properties.user_id
     *
     * @return the value of user_properties.user_id
     *
     * @mbggenerated Tue Oct 20 22:18:39 CST 2015
     */
    public Integer getUser_id() {
        return user_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_properties.user_id
     *
     * @param user_id the value for user_properties.user_id
     *
     * @mbggenerated Tue Oct 20 22:18:39 CST 2015
     */
    public void setUser_id(Integer user_id) {
        this.user_id = user_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_properties.status
     *
     * @return the value of user_properties.status
     *
     * @mbggenerated Tue Oct 20 22:18:39 CST 2015
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_properties.status
     *
     * @param status the value for user_properties.status
     *
     * @mbggenerated Tue Oct 20 22:18:39 CST 2015
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_properties.wealth
     *
     * @return the value of user_properties.wealth
     *
     * @mbggenerated Tue Oct 20 22:18:39 CST 2015
     */
    public Integer getWealth() {
        return wealth;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_properties.wealth
     *
     * @param wealth the value for user_properties.wealth
     *
     * @mbggenerated Tue Oct 20 22:18:39 CST 2015
     */
    public void setWealth(Integer wealth) {
        this.wealth = wealth;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_properties.create_date
     *
     * @return the value of user_properties.create_date
     *
     * @mbggenerated Tue Oct 20 22:18:39 CST 2015
     */
    public Date getCreate_date() {
        return create_date;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_properties.create_date
     *
     * @param create_date the value for user_properties.create_date
     *
     * @mbggenerated Tue Oct 20 22:18:39 CST 2015
     */
    public void setCreate_date(Date create_date) {
        this.create_date = create_date;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_properties.last_login_date
     *
     * @return the value of user_properties.last_login_date
     *
     * @mbggenerated Tue Oct 20 22:18:39 CST 2015
     */
    public Date getLast_login_date() {
        return last_login_date;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_properties.last_login_date
     *
     * @param last_login_date the value for user_properties.last_login_date
     *
     * @mbggenerated Tue Oct 20 22:18:39 CST 2015
     */
    public void setLast_login_date(Date last_login_date) {
        this.last_login_date = last_login_date;
    }
}