package com.kindle.kinbook.bean;

import java.util.Date;

public class UserDetail {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_detail.id
     *
     * @mbggenerated Tue Oct 20 22:18:39 CST 2015
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_detail.user_id
     *
     * @mbggenerated Tue Oct 20 22:18:39 CST 2015
     */
    private Integer user_id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_detail.gender
     *
     * @mbggenerated Tue Oct 20 22:18:39 CST 2015
     */
    private Integer gender;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_detail.birthday
     *
     * @mbggenerated Tue Oct 20 22:18:39 CST 2015
     */
    private Date birthday;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_detail.birthplace
     *
     * @mbggenerated Tue Oct 20 22:18:39 CST 2015
     */
    private String birthplace;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_detail.liveplace
     *
     * @mbggenerated Tue Oct 20 22:18:39 CST 2015
     */
    private String liveplace;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_detail.intro
     *
     * @mbggenerated Tue Oct 20 22:18:39 CST 2015
     */
    private String intro;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_detail.avatar
     *
     * @mbggenerated Tue Oct 20 22:18:39 CST 2015
     */
    private Integer avatar;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_detail.education
     *
     * @mbggenerated Tue Oct 20 22:18:39 CST 2015
     */
    private String education;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_detail.job_position
     *
     * @mbggenerated Tue Oct 20 22:18:39 CST 2015
     */
    private String job_position;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_detail.id
     *
     * @return the value of user_detail.id
     *
     * @mbggenerated Tue Oct 20 22:18:39 CST 2015
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_detail.id
     *
     * @param id the value for user_detail.id
     *
     * @mbggenerated Tue Oct 20 22:18:39 CST 2015
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_detail.user_id
     *
     * @return the value of user_detail.user_id
     *
     * @mbggenerated Tue Oct 20 22:18:39 CST 2015
     */
    public Integer getUser_id() {
        return user_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_detail.user_id
     *
     * @param user_id the value for user_detail.user_id
     *
     * @mbggenerated Tue Oct 20 22:18:39 CST 2015
     */
    public void setUser_id(Integer user_id) {
        this.user_id = user_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_detail.gender
     *
     * @return the value of user_detail.gender
     *
     * @mbggenerated Tue Oct 20 22:18:39 CST 2015
     */
    public Integer getGender() {
        return gender;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_detail.gender
     *
     * @param gender the value for user_detail.gender
     *
     * @mbggenerated Tue Oct 20 22:18:39 CST 2015
     */
    public void setGender(Integer gender) {
        this.gender = gender;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_detail.birthday
     *
     * @return the value of user_detail.birthday
     *
     * @mbggenerated Tue Oct 20 22:18:39 CST 2015
     */
    public Date getBirthday() {
        return birthday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_detail.birthday
     *
     * @param birthday the value for user_detail.birthday
     *
     * @mbggenerated Tue Oct 20 22:18:39 CST 2015
     */
    public void setBirthday(Date birthday) {
        this.birthday = birthday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_detail.birthplace
     *
     * @return the value of user_detail.birthplace
     *
     * @mbggenerated Tue Oct 20 22:18:39 CST 2015
     */
    public String getBirthplace() {
        return birthplace;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_detail.birthplace
     *
     * @param birthplace the value for user_detail.birthplace
     *
     * @mbggenerated Tue Oct 20 22:18:39 CST 2015
     */
    public void setBirthplace(String birthplace) {
        this.birthplace = birthplace;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_detail.liveplace
     *
     * @return the value of user_detail.liveplace
     *
     * @mbggenerated Tue Oct 20 22:18:39 CST 2015
     */
    public String getLiveplace() {
        return liveplace;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_detail.liveplace
     *
     * @param liveplace the value for user_detail.liveplace
     *
     * @mbggenerated Tue Oct 20 22:18:39 CST 2015
     */
    public void setLiveplace(String liveplace) {
        this.liveplace = liveplace;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_detail.intro
     *
     * @return the value of user_detail.intro
     *
     * @mbggenerated Tue Oct 20 22:18:39 CST 2015
     */
    public String getIntro() {
        return intro;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_detail.intro
     *
     * @param intro the value for user_detail.intro
     *
     * @mbggenerated Tue Oct 20 22:18:39 CST 2015
     */
    public void setIntro(String intro) {
        this.intro = intro;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_detail.avatar
     *
     * @return the value of user_detail.avatar
     *
     * @mbggenerated Tue Oct 20 22:18:39 CST 2015
     */
    public Integer getAvatar() {
        return avatar;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_detail.avatar
     *
     * @param avatar the value for user_detail.avatar
     *
     * @mbggenerated Tue Oct 20 22:18:39 CST 2015
     */
    public void setAvatar(Integer avatar) {
        this.avatar = avatar;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_detail.education
     *
     * @return the value of user_detail.education
     *
     * @mbggenerated Tue Oct 20 22:18:39 CST 2015
     */
    public String getEducation() {
        return education;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_detail.education
     *
     * @param education the value for user_detail.education
     *
     * @mbggenerated Tue Oct 20 22:18:39 CST 2015
     */
    public void setEducation(String education) {
        this.education = education;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_detail.job_position
     *
     * @return the value of user_detail.job_position
     *
     * @mbggenerated Tue Oct 20 22:18:39 CST 2015
     */
    public String getJob_position() {
        return job_position;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_detail.job_position
     *
     * @param job_position the value for user_detail.job_position
     *
     * @mbggenerated Tue Oct 20 22:18:39 CST 2015
     */
    public void setJob_position(String job_position) {
        this.job_position = job_position;
    }
}