package com.kindle.kinbook.bean;

import java.util.Date;

public class UserLog {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_log.id
     *
     * @mbggenerated Tue Oct 20 22:18:39 CST 2015
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_log.user_id
     *
     * @mbggenerated Tue Oct 20 22:18:39 CST 2015
     */
    private Integer user_id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_log.action_id
     *
     * @mbggenerated Tue Oct 20 22:18:39 CST 2015
     */
    private Integer action_id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_log.time
     *
     * @mbggenerated Tue Oct 20 22:18:39 CST 2015
     */
    private Date time;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_log.target
     *
     * @mbggenerated Tue Oct 20 22:18:39 CST 2015
     */
    private String target;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_log.id
     *
     * @return the value of user_log.id
     *
     * @mbggenerated Tue Oct 20 22:18:39 CST 2015
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_log.id
     *
     * @param id the value for user_log.id
     *
     * @mbggenerated Tue Oct 20 22:18:39 CST 2015
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_log.user_id
     *
     * @return the value of user_log.user_id
     *
     * @mbggenerated Tue Oct 20 22:18:39 CST 2015
     */
    public Integer getUser_id() {
        return user_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_log.user_id
     *
     * @param user_id the value for user_log.user_id
     *
     * @mbggenerated Tue Oct 20 22:18:39 CST 2015
     */
    public void setUser_id(Integer user_id) {
        this.user_id = user_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_log.action_id
     *
     * @return the value of user_log.action_id
     *
     * @mbggenerated Tue Oct 20 22:18:39 CST 2015
     */
    public Integer getAction_id() {
        return action_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_log.action_id
     *
     * @param action_id the value for user_log.action_id
     *
     * @mbggenerated Tue Oct 20 22:18:39 CST 2015
     */
    public void setAction_id(Integer action_id) {
        this.action_id = action_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_log.time
     *
     * @return the value of user_log.time
     *
     * @mbggenerated Tue Oct 20 22:18:39 CST 2015
     */
    public Date getTime() {
        return time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_log.time
     *
     * @param time the value for user_log.time
     *
     * @mbggenerated Tue Oct 20 22:18:39 CST 2015
     */
    public void setTime(Date time) {
        this.time = time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_log.target
     *
     * @return the value of user_log.target
     *
     * @mbggenerated Tue Oct 20 22:18:39 CST 2015
     */
    public String getTarget() {
        return target;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_log.target
     *
     * @param target the value for user_log.target
     *
     * @mbggenerated Tue Oct 20 22:18:39 CST 2015
     */
    public void setTarget(String target) {
        this.target = target;
    }
}